### ISSUE TITLE
Compatibility issue with active admin 1.x

### ISSUE THREAD

**Issue by adrienfairfaxmedia** [bolshakov/activeadmin-reform#19]
Hi @bolshakov ,

For dependency compatibility reasons I have to use activeadmin 1.x. Your gem doesn't appear to be compatible with activeadmin 1.x. I'm currently trying to update it but I'm facing some issues with the "has_many" activeadmin form helper. I didn't test that it actually works with activeadmin 0.6, could you confirm that?

**Comment by bolshakov** [comment]
Hi,

I'm sorry, but the gem doesn't work with older versions of AA, since it depends on [this changes](https://github.com/activeadmin/activeadmin/pull/4166).

**Comment by adrienfairfaxmedia** [comment]
Sorry for any reason I got confused.

So now I'm using AA from master branch with your gem from master branch. But I cannot get the "has_many" activeadmin form helper to work.

``` ruby
class Item
  has_one :contact
end
```

``` ruby
class Contact
  belongs_to :Item
end
```

``` ruby
class MyForm < Reform::Form
  include Reform::Form::ModelReflections
  property :name
  property :description
  property :contact, , populate_if_empty: Contact do
    property :email
  end
end
```

And then in my activeadmin item file I have this form:

``` ruby
  form do |f|
    f.semantic_errors
    f.inputs :name, :description
    f.has_many :contact do |contact|
      contact.inputs :email
    end
    f.actions
  end
```

But when I go on the edit page of an an item I have that weird error:

```
undefined method `new_record?' for #<#<Class:0x007fb435e6b0b8>:0x007fb432dd2820>
```

any idea?

![screen shot 2016-05-11 at 10 25 39 am](https://cloud.githubusercontent.com/assets/19256838/15166479/9a286cf6-1762-11e6-82e1-3ade91b9f9b3.png)

**Comment by bolshakov** [comment]
When you're trying to use Reform wrapper instead of ActiveRecord object, AA still tries to call some ActiveRecord specific methods on forms.

To avoid this issue, you have to define `#new_record?` method on your form.

``` ruby
class ListingAdvertForm < Reform::Form
  delegate :new_record?, to: :model
end
```

I have the following module, included in all my forms:

``` ruby
module ModelReflections
  extend ActiveSupport::Concern
  include Reform::Form::ActiveModel::ModelReflections

  delegate :new_record?, to: :model

  class_methods do
    delegate :human_attribute_name, to: :model_class
    delegate :lookup_ancestors, to: :model_class

    def model_class
      @model_class ||= model_name.name.constantize
    end
  end
end
```

It solves most compatibility issues with ActiveRecord.

**Comment by adrienfairfaxmedia** [comment]
Thanks heaps @bolshakov . It's working now, I'll close the issue.

**Comment by bolshakov** [comment]
@adrienfairfaxmedia you are welcome :)
